#pragma once

#include "genetic_algorithm/breeding.hpp"
#include "genetic_algorithm/device/buffer_runtime.hpp"
#include "genetic_algorithm/fitness_evaluation.hpp"
#include "genetic_algorithm/generation_assembly.hpp"
#include "genetic_algorithm/genome.hpp"
#include "genetic_algorithm/genotype_buffer/assembly.hpp"
#include "genetic_algorithm/genotype_buffer/buffer.hpp"
#include "genetic_algorithm/genotype_buffer/device_runtime.hpp"
#include "genetic_algorithm/genotype_buffer/generation.hpp"
#include "genetic_algorithm/genotype_buffer/reference_counter.hpp"
#include "genetic_algorithm/genotype_buffer/repacking.hpp"
#include "genetic_algorithm/mutation.hpp"
#include "genetic_algorithm/output_embedding_injection.hpp"
#include "genetic_algorithm/population.hpp"
#include "genetic_algorithm/population_initialization.hpp"
#include "genetic_algorithm/selection.hpp"
