#pragma once

#include "genetic_algorithm/breeding.hpp"
#include "genetic_algorithm/fitness_evaluation.hpp"
#include "genetic_algorithm/generation_assembly.hpp"
#include "genetic_algorithm/genome.hpp"
#include "genetic_algorithm/genotype_arena/arena.hpp"
#include "genetic_algorithm/genotype_arena/assembly.hpp"
#include "genetic_algorithm/genotype_arena/device_runtime.hpp"
#include "genetic_algorithm/genotype_arena/generation.hpp"
#include "genetic_algorithm/mutation.hpp"
#include "genetic_algorithm/output_embedding_injection.hpp"
#include "genetic_algorithm/population.hpp"
#include "genetic_algorithm/population_initialization.hpp"
#include "genetic_algorithm/selection.hpp"
