#pragma once

#include "genetic_algorithm/breeding.hpp"
#include "genetic_algorithm/device/pool_runtime.hpp"
#include "genetic_algorithm/fitness_evaluation.hpp"
#include "genetic_algorithm/generation_assembly.hpp"
#include "genetic_algorithm/genome.hpp"
#include "genetic_algorithm/genotype_pool/assembly.hpp"
#include "genetic_algorithm/genotype_pool/device_runtime.hpp"
#include "genetic_algorithm/genotype_pool/generation.hpp"
#include "genetic_algorithm/genotype_pool/pool.hpp"
#include "genetic_algorithm/genotype_pool/repacking.hpp"
#include "genetic_algorithm/mutation.hpp"
#include "genetic_algorithm/output_embedding_injection.hpp"
#include "genetic_algorithm/population.hpp"
#include "genetic_algorithm/population_initialization.hpp"
#include "genetic_algorithm/selection.hpp"
